name: getx_gallery
description: GetX Gallery

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  permission_handler: ^6.1.1
  isolate_handler: ^1.0.0
  flutter:
    sdk: flutter
  get: ^4.1.3
  collection: ^1.15.0
  json_serializable: ^4.1.0
  photo_view: ^0.11.1
  path_provider: ^2.0.1
  path: ^1.8.0
  hive_flutter: ^1.0.0
  hive: ^2.0.2
  shared_preferences: ^2.0.5

dev_dependencies:
  build_runner: ^1.12.2
  flutter_test:
    sdk: flutter
  hive_generator: ^1.0.1
  lint: ^1.5.3

flutter:
  uses-material-design: true