name: getx_gallery
description: test of getx

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  permission_handler: ^6.1.1
  watcher: ^1.0.0
  path_provider_ex:
    path: "plugins/path_provider_ex"
  hive: ^2.0.2
  isolate_handler: ^1.0.0
  flutter:
    sdk: flutter
  get: ^4.1.3
  image: ^3.0.2
  thumbnailer: ^2.0.0
  collection: ^1.15.0
  json_serializable: ^4.1.0
  photo_view: ^0.11.1
  path_provider: ^2.0.1
  path: ^1.8.0
  hive_flutter: ^1.0.0

dev_dependencies:
  build_runner: ^1.12.2
  flutter_test:
    sdk: flutter
  hive_generator: ^1.0.1
  lint: ^1.5.3

flutter:
  uses-material-design: true